### ISSUE TITLE
Zoom controls on graphs

### ISSUE THREAD

**Issue by Alex-Potter-Dixon** [icatproject/dashboard#11]
Add + , - and Reset buttons for zooming on graphs

**Comment by Alex-Potter-Dixon** [comment]
With the c3.js library you are unable to set Zoom values so having a simple + and - wouldn't work as the API does not allow this to work. I think the reason this is like this is because it zooms based off the domain (location on the graph) and the domain is specified by where your mouse pointer is. With a button no domain is specified hence no ability to zoom.

As this is not possible with the current library then I am not sure what would be the next stage with this feature request.

**Comment by tomgriffinstfc** [comment]
is 'reset' possible?

**Comment by Alex-Potter-Dixon** [comment]
There is an unzoom that may be used. I will have to rewrite all of my directives to accompany this feature but it will pave the way for more dynamic graphs.
There may also be a zoom function that may be used but from the documentation it is unclear if it would work for the required requirement.
