### ISSUE TITLE
Data being displayed on each page should be downloadable.

### ISSUE THREAD

**Issue by Alex-Potter-Dixon** [icatproject/dashboard#38]
Not sure what format it should be displayed in. 

It would make sense to print the raw data returned from the API as it would be the most logical to view (Currently JSON). Currently a lot of the data is mapped into arrays to allow C3 to read it if this was printed it might be difficult to read. Any suggestions would be great.

**Comment by tomgriffinstfc** [comment]
What is the underlying requirement? (perhaps as a user story)

**Comment by Alex-Potter-Dixon** [comment]
As a user I want to be able to download the data that I have selected through the dashboard so that I can do further analysis on the data. 

This does point it more to csv for excel.
