### ISSUE TITLE
Code uses untyped database queries

### ISSUE THREAD

**Issue by fisherab** [icatproject/dashboard#77]
Use TypedQuery to get rid of a lot of warnings and to make the code safer

**Comment by tg137** [comment]
I'm not editing in Eclipse, but if you change:

`Object[] entities = manager.createQuery(query).getResultList();`

Into:

`TypedQuery<Object[]> typedQuery = manager.createQuery(query);`

`List<Object[]> entities = typedQuery.getResultList();`

Does that solve the problem?

**Comment by fisherab** [comment]
No.

Probably easiest if I show you.

Steve
